matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      dist: focal

      addons:
        apt:
          packages:
            - libsdl2-dev

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip

      script:
        - go build -tags sdl,static -ldflags "-s -w" virtualxt.go
        - ./tools/package/itch/package.linux.sh

    ################ Linux Snap Build ################

    - name: Linux (snap)
      #if: branch = release OR branch = edge
      if: branch = master
      os: linux
      dist: bionic
      sudo: required

      addons:
        snaps:
          - name: multipass
          - name: snapcraft
            confinement: classic

      install:
        - export PUSH_SNAP=1

      script:
        - sudo chown $USER:$USER /var/snap/multipass/common/multipass_socket

        #- echo $SNAPCRAFT_LOGIN_FILE | base64 --decode --ignore-garbage > snapcraft.login
        #- snapcraft login --with snapcraft.login

        - snapcraft

    ################ OSX Build ################

    - name: OSX
      os: osx
      osx_image: xcode12

      addons:
        homebrew:
          packages:
            - sdl2
            - rpl

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip

      script:
        - go build -tags sdl,static -ldflags "-s -w" virtualxt.go
        - ./tools/package/itch/package.osx.sh

    ################ Windows Build ################

    - name: Windows
      os: windows

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o sdl.tar.gz https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz
        - 7z x sdl.tar.gz && 7z x sdl.tar

        - export C_INCLUDE_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/include
        - export LIBRARY_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/lib

        - go get github.com/akavel/rsrc

      script:
        - rsrc -ico=doc/icon/icon.ico -arch=amd64
        - go build -tags sdl,static -ldflags "-s -w" virtualxt.go
        - ./tools/package/itch/package.bat

################ Common ################

language: go

go:
  - "1.14.x"

env:
  - VXT_VERSION=0.5.0

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

before_script:
  - export FULL_VERSION=${VXT_VERSION}.${TRAVIS_BUILD_ID}
  - go generate ./...
  - go test -race -coverprofile coverage.txt -covermode atomic ./...
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  skip_cleanup: true
  script: bash tools/package/itch/push.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(edge|release)$