matrix:
  include:

    ################ Linux Build ################

    - name: Linux
      os: linux
      dist: bionic

      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o sdl2.tar.gz https://www.libsdl.org/release/SDL2-2.0.10.tar.gz && tar xf sdl2.tar.gz

        #- cd SDL2-* && ./configure && make && sudo make install && cd $TRAVIS_BUILD_DIR
    
      script:
        - go build -tags sdl,static -ldflags "-s -w" virtualxt.go
        #- go build -tags sdl virtualxt.go
        - ./tools/package/itch/package.linux.sh

    ################ OSX Build ################

    - name: OSX
      os: osx
      osx_image: xcode10.1

      addons:
        homebrew:
          update: true
          packages:
            - sdl2
            - pkg-config
            - rpl

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/darwin-amd64/LATEST/archive/default && unzip butler.zip

      script:
        - go build -tags sdl,static -ldflags "-s -w" virtualxt.go
        - ./tools/package/itch/package.osx.sh

    ################ Windows Build ################

    - name: Windows
      os: windows

      install:
        - curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip
        - curl -L -o sdl.tar.gz https://www.libsdl.org/release/SDL2-devel-2.0.10-mingw.tar.gz
        - 7z x sdl.tar.gz && 7z x sdl.tar

        - export C_INCLUDE_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/include
        - export LIBRARY_PATH=${TRAVIS_BUILD_DIR}/SDL2-2.0.10/x86_64-w64-mingw32/lib

        - go get github.com/akavel/rsrc

      script:
        - rsrc -ico=doc/icon/icon.ico -arch=amd64
        - go build -tags sdl,static -ldflags "-s -w" virtualxt.go
        - ./tools/package/itch/package.bat

################ Common ################

language: go

go:
  - "1.14.x"

env:
  - VXT_VERSION=0.5.0

notifications:
  email:
    on_success: never
    on_failure: change

before_install:
  - export PATH=$TRAVIS_BUILD_DIR:$PATH

before_script:
  - export FULL_VERSION=${VXT_VERSION}.${TRAVIS_BUILD_ID}
  - go generate ./...
  - go test ./...

deploy:
  provider: script
  skip_cleanup: true
  script: bash tools/package/itch/push.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(edge|release)$