[[actions]]
name = "VirtualXT - FreeDOS"
#path = "VirtualXT.app"
path = "Launch.sh"

#[[actions]]
#name = "Boot Floppy Image"
#path = "VirtualXT.app"

#[[actions]]
#name = "manual"
#path = "VirtualXT.app/Contents/Resources/manual/index.html"