name: virtualxt
version: 0.6.2
summary: Lightweight IBM PC/XT emulator
icon: tools/package/snap/usr/share/icons/hicolor/128x128/apps/virtualxt.png
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: i386
license: Zlib
description: |
  VirtualXT is an IBM PC/XT emulator that runs on modern hardware and operating systems.
  It is designed to be simple and lightweight yet still capable enough to run a large library of old application and games.

base: core18
grade: stable
confinement: strict

parts:
  desktop:
    source: tools/package/snap
    plugin: dump
    prime:
      - usr

  boot:
    source: boot
    plugin: dump
    prime:
      - usr
    organize:
      freedos.img: usr/share/virtualxt/boot/freedos.img
      freedos_hd.img: usr/share/virtualxt/boot/freedos_hd.img

  bios:
    source: bios
    plugin: dump
    prime:
      - usr
    organize:
      pcxtbios.bin: usr/share/virtualxt/bios/pcxtbios.bin
      vxtx.bin: usr/share/virtualxt/bios/vxtx.bin

  manual:
    source: doc
    plugin: dump
    prime:
      - usr
    organize:
      manual: usr/share/virtualxt/manual

  alsa-lib:
    plugin: autotools
    source: http://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.6.1.tar.bz2
    configflags:
      - --prefix=/usr
      - --sysconfdir=/etc
      - --libexec=/usr/lib
      - --libdir=/usr/lib
      - --localstatedir=/var
      - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
      - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
      - --disable-static
    stage:
      - usr/include
      - usr/lib
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/pkgconfig
      - -usr/share/alsa/alsa.conf
      - -usr/share/alsa/pcm
      - -usr/share/alsa/topology/broadwell

  virtualxt:
    after:
      - alsa-lib
    stage:
      - usr/bin
      - usr/lib
    organize:
      bin/virtualxt: usr/bin/virtualxt
    source: .
    plugin: go
    go-buildtags: [sdl, pcap]
    go-packages: [github.com/andreas-jonsson/virtualxt]
    build-packages: [gcc, pkg-config, libsdl2-dev, libpcap0.8-dev]
    stage-packages:
      #- libasound2
      - libasyncns0
      - libflac8
      - libogg0
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libsndio6.1
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxxf86vm1
      - libpcap0.8
    prime:
      - usr/bin
      - -usr/bin/X11
      - usr/lib
      - -usr/lib/X11
      - -usr/lib/pkgconfig

#layout:
#  /usr/share/alsa/alsa.conf:
#    symlink: $SNAP/usr/share/alsa/alsa.conf

apps:
  virtualxt:
    command: usr/bin/virtualxt.freedos
    desktop: usr/share/applications/virtualxt.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback
      - alsa
      - joystick
      - home
      - removable-media
    environment:
      ALSA_CONFIG_PATH: "/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa"
      LD_LIBRARY_PATH: "${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio"
