name: virtualxt
version: 0.7.0
summary: Lightweight IBM PC/XT emulator
icon: tools/package/snap/usr/share/icons/hicolor/128x128/apps/virtualxt.png
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: i386
license: zlib-acknowledgement
description: |
  VirtualXT is an IBM PC/XT emulator that runs on modern hardware and operating systems.
  It is designed to be simple and lightweight yet still capable enough to run a large library of old application and games.

base: core22
grade: stable
confinement: strict

parts:
  desktop:
    source: tools/package/snap
    plugin: dump
    prime:
      - usr

  boot:
    source: boot
    plugin: dump
    prime:
      - usr
    organize:
      freedos.img: usr/share/virtualxt/boot/freedos.img
      freedos_hd.img: usr/share/virtualxt/boot/freedos_hd.img

  bios:
    source: bios
    plugin: dump
    prime:
      - usr
    organize:
      pcxtbios.bin: usr/share/virtualxt/bios/pcxtbios.bin
      glabios.bin: usr/share/virtualxt/bios/glabios.bin
      vxtx.bin: usr/share/virtualxt/bios/vxtx.bin

  virtualxt:
    stage:
      - usr/bin
      - usr/lib
    organize:
      build/bin/virtualxt: usr/bin/virtualxt
    source: .
    plugin: nil
    override-build: |
      snap install zig --classic --beta
      zig build -Drelease-fast -Dv20
    build-packages: [gcc, pkg-config, libsdl2-dev, libpcap0.8-dev]
    stage-packages:
      - libasound2
      - libasyncns0
      - libflac8
      - libogg0
      - libpulse0
      - libsdl2-2.0-0
      - libsndfile1
      - libvorbis0a
      - libvorbisenc2
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1
      - libxss1
      - libxxf86vm1
      - libpcap0.8
    prime:
      - usr/bin
      - -usr/bin/X11
      - usr/lib
      - -usr/lib/X11
      - -usr/lib/pkgconfig

apps:
  virtualxt:
    command: usr/bin/virtualxt.freedos
    desktop: usr/share/applications/virtualxt.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback
      - joystick
      - home
      - removable-media
    environment:
      LD_LIBRARY_PATH: "${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/pulseaudio"
