name: Libretro

on:
  push:
    branches: [ "develop", "edge", "release" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  VXT_VERSION: 0.8.0
  ZIG_VERSION: 0.10.1
  ZIG_ARCHS: "x86_64-linux-gnu i386-linux-gnu aarch64-linux-gnu arm-linux-gnueabi x86_64-macos-none aarch64-macos-none"
  NDK_VERSION: r20
  NDK_ARCHS: "aarch64-linux-android armv7a-linux-androideabi x86_64-linux-android i686-linux-android"

jobs:
  libretro-build:
    name: Libretro (Unix)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup
        run: |
          curl -L -o ndk.zip https://dl.google.com/android/repository/android-ndk-${NDK_VERSION}-linux-x86_64.zip && unzip ndk.zip
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip -d butler
          curl -L -o premake5.tar.gz https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-linux.tar.gz && mkdir premake5 && tar -xf premake5.tar.gz -C premake5
          curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz
          echo "${GITHUB_WORKSPACE}/zig-linux-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/butler" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/premake5" >> $GITHUB_PATH

      - name: Test
        run: |
          premake5 --test gmake
          make clean test

      - name: Premake
        run: |
          premake5 --cc=clang gmake
          mkdir -p package/virtualxt
          cp front/libretro/*.info package/virtualxt

      - name: Build
        env:
          CLANG_PATH: "${GITHUB_WORKSPACE}/android-ndk-${NDK_VERSION}/toolchains/llvm/prebuilt/linux-x86_64/bin"
        run: |
          for arch in `cat ${ZIG_ARCHS}`; do
            echo Building ${arch}...
            rm -rf build/lib
            make CC="zig cc -target ${arch}" AR="zig ar" RANLIB="zig ranlib" clean libretro-frontend
            mkdir package/virtualxt/${arch}
            cp build/lib/*.so package/virtualxt/${arch}
          done

          for arch in `cat ${NDK_ARCHS}`; do
            echo Building ${arch}...
            rm -rf build/lib
            make CC="${CLANG_PATH}/${arch}21-clang" LD="${CLANG_PATH}/${arch}-ld" AR="${CLANG_PATH}/${arch}-ar" clean libretro-frontend
            mkdir package/virtualxt/${arch}
            cp build/lib/*.so package/virtualxt/${arch}
          done

      - name: Package
        run: |
          cd package
          zip -r ../virtualxt.zip .
          cd ..

      - name: Deploy
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: if [[ $GITHUB_REF_NAME =~ ^(edge|release)$ ]]; then ./tools/package/itch/push-libretro.sh; fi

  windows-build:
    name: Libretro (Windows)
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: base-devel mingw-w64-x86_64-toolchain
      
      - name: Setup
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/windows-amd64/LATEST/archive/default && unzip butler.zip -d butler
          curl -L -o premake5.zip https://github.com/premake/premake-core/releases/download/v5.0.0-beta2/premake-5.0.0-beta2-windows.zip && mkdir premake5 && unzip premake5.zip -d premake5
          echo "${GITHUB_WORKSPACE}/premake5" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/butler" >> $GITHUB_PATH

      - name: Test
        shell: msys2 {0}
        run: |
          export PATH="${GITHUB_WORKSPACE}/premake5":"$PATH"
          premake5 --test --cc=gcc gmake
          make clean test
      
      - name: Premake
        shell: msys2 {0}
        run: |
          export PATH="${GITHUB_WORKSPACE}/premake5":"$PATH"
          premake5 --cc=gcc gmake
      
      - name: Build
        shell: msys2 {0}
        run: |
          make clean libretro-frontend
          mkdir -p package/virtualxt
          cp build/lib/*.dll package/virtualxt
          cp front/libretro/*.info package/virtualxt

      - name: Package & Deploy
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: if [[ $GITHUB_REF_NAME =~ ^(edge|release)$ ]]; then ./tools/package/itch/push-libretro.sh; fi
