name: Pages

on:
  push:
    branches: [ "edge" ]

  workflow_dispatch:

env:
  ZIG_VERSION: 0.10.0

jobs:
  linux-pages:
    name: Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup
        run: |
          sudo apt-get update
          sudo apt-get install doxygen
          curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz
          echo "${GITHUB_WORKSPACE}/zig-linux-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
      
      - name: Test
        run: zig build test

      - name: Build
        run: zig build web -Drelease-fast -Dv20

      - name: Docs
        run: zig build doc

      - name: Package
        run: |
          rm build/web/*.o
          mkdir gh-pages
          cp -r docs gh-pages
          cp -r build/web gh-pages

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: gh-pages
