name: Web

on:
  push:
    branches: [ "develop", "edge", "release" ]
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

env:
  VXT_VERSION: 0.7.0
  ZIG_VERSION: 0.10.0

jobs:
  web-build:
    name: Web (Linux AMD64)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x

      - name: Setup
        run: |
          curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default && unzip butler.zip -d butler
          curl -L -o zig.tar.xz https://ziglang.org/download/${ZIG_VERSION}/zig-linux-x86_64-${ZIG_VERSION}.tar.xz && tar -xf zig.tar.xz
          echo "${GITHUB_WORKSPACE}/zig-linux-x86_64-${ZIG_VERSION}" >> $GITHUB_PATH
          echo "${GITHUB_WORKSPACE}/butler" >> $GITHUB_PATH

      - name: Test
        run: zig build test

      - name: Build
        run: zig build web -Drelease-fast=true

      - name: Package
        run: |
          cd build/web
          rm *.o
          zip -r ../../virtualxt.zip .
          cd ../..
        
      - name: Deploy
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        run: if [[ $GITHUB_REF_NAME =~ ^(edge)$ ]]; then ./tools/package/itch/push-web.sh; fi
